// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingSofka.Web.Data;

namespace TrainingSofka.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200903214203_AddEntitiesNew")]
    partial class AddEntitiesNew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrainingSofka.Web.Data.Entities.EquipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlightEntityId");

                    b.Property<double>("Peso");

                    b.Property<double>("TotalEquipment");

                    b.Property<int>("ValueDolars");

                    b.Property<double>("ValuePesos");

                    b.HasKey("Id");

                    b.HasIndex("FlightEntityId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("TrainingSofka.Web.Data.Entities.FlightEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("TrainingSofka.Web.Data.Entities.TravelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Days");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Discount");

                    b.Property<double>("Distance");

                    b.Property<double>("Total");

                    b.HasKey("Id");

                    b.ToTable("Travels");
                });

            modelBuilder.Entity("TrainingSofka.Web.Data.Entities.EquipmentEntity", b =>
                {
                    b.HasOne("TrainingSofka.Web.Data.Entities.FlightEntity", "FlightEntity")
                        .WithMany("Equipments")
                        .HasForeignKey("FlightEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
